apiVersion: stable.dwk/v1
kind: Dummysite
metadata:
  name: wiki
  namespace: default
spec:
  website_url: 'https://en.wikipedia.org/wiki/Special:Random'
  # website_url: 'http://example.com'
---
apiVersion: stable.dwk/v1
kind: Dummysite
metadata:
  name: example
  namespace: test
spec:
  website_url: 'http://example.com'
