apiVersion: v1
kind: Service
metadata:
  name: dummy-site-svc
spec:
  type: ClusterIP # for ingress and for GKE Gateway, use NodePort if directly with (GKE) LoadBalancer
  selector:
    app: dummy-site
  ports: # will let TCP traffic from port 1234 to port 80
    - port: 1234
      protocol: TCP
      targetPort: 80
