apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: pingpong-route
  namespace: exercises
spec:
  parentRefs:
    - name: pingpong-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /pingpong
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch # so IP/pingpong will lead to pingpong-svc:1234/ aka backend /
              replacePrefixMatch: /
      backendRefs:
        - name: pingpong-svc
          port: 1234
