apiVersion: v1
kind: Service
metadata:
  name: pingpong-svc
  namespace: exercises
spec:
  type: NodePort
  selector:
    app: pingpong
  ports: # will let TCP traffic from port 80 (ingress), could also be 1234 to port 3002
    - port: 80
      protocol: TCP
      targetPort: 3002 #check env in deployment
