apiVersion: v1
kind: Service
metadata:
  name: counter-svc
spec:
  type: ClusterIP
  selector:
    app: pingpong
  ports: # will let TCP traffic from port 3456 to port 3002
    - port: 3456
      protocol: TCP
      targetPort: 3002
