apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: greeters-route
spec:
  parentRefs:
    - group: ''
      kind: Service
      name: greeter-svc
      port: 3456
  rules:
    - backendRefs:
        - name: greeter-svc-v1
          port: 3456
          weight: 75
        - name: greeter-svc-v2
          port: 3456
          weight: 25

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeter-dep-v1
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeter
      version: v1
  template:
    metadata:
      labels:
        app: greeter
        version: v1
    spec:
      containers:
        - name: greeter
          image: thomastoumasu/k8s-greeter:5.3
          env:
            - name: PORT
              value: '3004'
            - name: VERSION
              value: '1'
---
apiVersion: v1
kind: Service
metadata:
  name: greeter-svc-v1
spec:
  type: ClusterIP
  selector:
    app: greeter
    version: v1
  ports:
    - port: 3456
      protocol: TCP
      targetPort: 3004
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeter-dep-v2
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeter
      version: v2
  template:
    metadata:
      labels:
        app: greeter
        version: v2
    spec:
      containers:
        - name: greeter
          image: thomastoumasu/k8s-greeter:5.3
          env:
            - name: PORT
              value: '3004'
            - name: VERSION
              value: '2'
---
apiVersion: v1
kind: Service
metadata:
  name: greeter-svc-v2
spec:
  type: ClusterIP
  selector:
    app: greeter
    version: v2
  ports:
    - port: 3456
      protocol: TCP
      targetPort: 3004
