apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: the-project-infra
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/thomastoumasu/k8s-submission/
    path: ./the_project/kustomize/infra/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
