apiVersion: apps/v1
kind: Deployment
metadata:
  name: dwk-environments
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dwk-environments
  template:
    metadata:
      labels:
        app: dwk-environments
    spec:
      containers:
        - name: dwk-environments
          image: PROJECT/IMAGE # see kustomization.yaml in the root folder
