apiVersion: v1
kind: Service
metadata:
  name: dwk-environments-svc
  namespace: exercises
spec:
  type: LoadBalancer
  selector:
    app: dwk-environments
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
