apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/gateway.yaml
  - mongo/manifests/config-map.yaml
  - mongo/manifests/statefulset_gke.yaml
  - backend/manifests/deployment_gke_gat.yaml
  - backend/manifests/route_gke.yaml
  - manifests/persistentvolumeclaim_gke.yaml
  - image-finder/manifests/deployment_gke.yaml
  - frontend/manifests/deployment_gke_gat.yaml
  - frontend/manifests/route_gke.yaml
