apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
  namespace: exercises
spec:
  replicas: 2
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes: # You set volumes at the Pod level, then mount them into containers inside that Pod
        - name: config
          configMap: # Provide the name of the ConfigMap you want to mount.
            name: log-output-cfgmp
            items: # An array of keys from the ConfigMap to create as files
              - key: 'information.txt'
                path: 'information.txt'
      containers:
        - name: log-output
          image: thomastoumasu/k8s-log-output:4.1b-amd
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-cfgmp # The ConfigMap this value comes from.
                  key: MESSAGE # The key to fetch.
          volumeMounts:
            - name: config
              mountPath: '/config'
              readOnly: true
          readinessProbe:
            initialDelaySeconds: 10 # Initial delay until the readiness is tested
            periodSeconds: 5 # How often to test
            httpGet:
              path: /health
              port: 3000
          livenessProbe:
            initialDelaySeconds: 20 # Initial delay until the liveness is tested
            periodSeconds: 5 # How often to test
            httpGet:
              path: /health
              port: 3000
