apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: log-output
  namespace: exercises
spec:
  template:
    spec:
      volumes: # You set volumes at the Pod level, then mount them into containers inside that Pod
        - name: config
          configMap: # Provide the name of the ConfigMap you want to mount.
            name: log-output-cfgmp
            items: # An array of keys from the ConfigMap to create as files
              - key: 'information.txt'
                path: 'information.txt'
      containers:
        - name: log-output
          # image: thomastoumasu/k8s-log-output:5.3b # this image works also for k3s
          image: thomastoumasu/k8s-log-output:buildx-latest
          env:
            - name: GREETER_URL
              # value: 'http://greeter-svc:3456/' # this was the url before serverless
              value: 'http://greeter.exercises.svc.cluster.local/'
            - name: PINGPONG_URL
              # value: 'http://pingpong-svc:1234/counter' # this was the url before serverless
              # value: 'http://pingpong.exercises.35.228.143.21.sslip.io/counter' # this also work but would need to be adapted for each new cluster
              value: 'http://pingpong.exercises.svc.cluster.local/counter'
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-cfgmp # The ConfigMap this value comes from.
                  key: MESSAGE # The key to fetch.
          volumeMounts:
            - name: config
              mountPath: '/config'
              readOnly: true
