apiVersion: v1
kind: Service
metadata:
  name: log-output-svc
  namespace: exercises
spec:
  type: NodePort
  selector:
    app: log-output
  ports: # will let TCP traffic from port 80 (ingress) to port 3000
    - port: 80
      protocol: TCP
      targetPort: 3000 #check env in deployment
