name: Backup db
on:
  push:
  # schedule:
  # - cron: "* * * * *"

env:
  BUCKET: thomastoumasu_k8s-bucket
  MONGO_URI: mongodb://the_username:the_password@mongo-svc.project:27017/the_database

jobs:
  backup-db:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2

      - name: 'Use gcloud CLI'
        run: gcloud info

      - name: 'Setup mongodb-tools'
        run: |
          wget https://fastdl.mongodb.org/tools/db/mongodb-database-tools-ubuntu2204-x86_64-100.6.1.deb
          sudo apt install ./mongodb-database-tools-*-100.6.1.deb
          mongorestore --version

      # - name: Create test file
      #   run: >-
      #     echo \
      #     '[
      #       {
      #         "name": "delete-branch-images",
      #         "action": { "type": "Delete" },
      #         "condition": {
      #           "tagState": "tagged",
      #           "tagPrefixes": ["yeah"]
      #         }
      #       }
      #     ]'
      #     > delete-policy.json

      # - name: Send File to Google Global Storage
      #   run: gcloud storage cp delete-policy.json gs://${BUCKET}

      - name: 'Dump'
        run: mongodump --uri=$MONGO_URI --out $(pwd)

      - name: 'Set current date as env variable'
        # run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
        run: |
          NOW=$(date +'%Y-%m-%dT%H-%M-%S')
          echo "FILENAME="./the_database/todos-${NOW}.bson"" >> $GITHUB_ENV

      - name: 'Rename dump'
        run: mv ./the_database/todos.bson $FILENAME

      - name: 'Send Dump to Google Global Storage'
        run: gcloud storage cp $FILENAME gs://${BUCKET}
